//! Generate the IDL using Anchor's own compiled Rust metadata, without Anchor CLI.
use anchor_lang_idl::build::IdlBuilder;
use std::{env, fs, path::PathBuf};

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let program = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    // IdlBuilder 0.1.4 passes a literal '+{toolchain}' when this variable is set.
    // The pinned rust-toolchain.toml still selects 1.89 for its child Cargo process.
    env::remove_var("RUSTUP_TOOLCHAIN");
    let idl = IdlBuilder::new()
        .program_path(program.clone())
        .cargo_args(vec!["--lib".into(), "--locked".into()])
        .build()?;
    assert_eq!(idl.address, fuse_escrow::ID.to_string());
    let directory = program.parent().unwrap().parent().unwrap().join("idl");
    fs::create_dir_all(&directory)?;
    let json = serde_json::to_string_pretty(&idl)?;
    fs::write(directory.join("fuse_escrow.json"), format!("{json}\n"))?;
    fs::write(directory.join("fuse_escrow.ts"), format!(
        "// Generated by export_idl from the compiled Rust program. Do not edit.\nexport type FuseEscrow = {json};\n"
    ))?;
    println!(
        "Generated Rust-authoritative IDL and TypeScript interface for {}",
        idl.address
    );
    Ok(())
}
