[toolchain]
anchor_version = "0.32.1"
solana_version = "2.3.0"

[features]
resolution = true
skip-lint = false

[programs.localnet]
fuse_escrow = "25GSneHPbwgwoUNjjcGQ4RoJzJsxETMtZUHNhXWYTf7G"

[programs.devnet]
fuse_escrow = "6R4NM7PX1jy2E3BhLohh2eoQaF2ubkwW6iNrmgYGViHf"

[provider]
cluster = "localnet"
wallet = ".wallets/local-only.json"

[scripts]
test = "bash scripts/run-linux.sh test"
