import {
  address,
  getAddressDecoder,
  getAddressEncoder,
  getBooleanDecoder,
  getI64Decoder,
  getStructDecoder,
  getU64Decoder,
  getU8Decoder,
  transformDecoder,
  type Address,
  type FixedSizeDecoder,
} from "@solana/kit";
import idl from "../../anchor/idl/fuse_escrow.json";
import devnetIdl from "../../anchor/idl/devnet/fuse_escrow.json";
import type { FuseEscrow } from "../../anchor/idl/fuse_escrow";

// Generated by Anchor's Rust IDL builder. Never hand-maintain discriminators.
export const FUSE_IDL: FuseEscrow = idl as FuseEscrow;
export const PROGRAM_ID = address(FUSE_IDL.address);
export const DEVNET_PROGRAM_ID = address(devnetIdl.address);
export const DEVNET_RPC = "https://api.devnet.solana.com";
export const DEVNET_GENESIS = "EtWTRABZaYq6iMfeYKouRu166VU2xqa1wcaWoxPkrZBG";
export type DemoNetwork = "localnet" | "devnet";
export interface NetworkConfig {
  rpcUrl: string;
  programId: Address;
  network: DemoNetwork;
}
export function explorerLink(kind: "address" | "tx", value: string): string {
  return `https://explorer.solana.com/${kind}/${encodeURIComponent(value)}?cluster=devnet`;
}
export const TOKEN_PROGRAM = address(
  "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
);
export const ACTIVATION = FUSE_IDL.instructions.find(
  (ix) => ix.name === "activate",
)!;
const campaignType = FUSE_IDL.types.find((type) => type.name === "Campaign")!;
const statuses = FUSE_IDL.types.find((type) => type.name === "CampaignStatus")!;
export type CampaignStatus = (typeof statuses.type.variants)[number]["name"];
export interface CampaignData {
  organizer: Address;
  identifier: bigint;
  mint: Address;
  seat_price: bigint;
  required_seats: bigint;
  target_amount: bigint;
  deadline: bigint;
  venue: Address;
  instructor: Address;
  venue_allocation: bigint;
  instructor_allocation: bigint;
  bump: number;
  vault_bump: number;
  venue_approved: boolean;
  instructor_approved: boolean;
  funded_seats: bigint;
  escrowed_amount: bigint;
  status: CampaignStatus;
}

// The limited codec deliberately rejects new/unsupported IDL types rather than
// silently decoding a changed program. Field order comes from the generated IDL.
function fieldDecoder(
  type: (typeof campaignType.type.fields)[number]["type"],
): FixedSizeDecoder<unknown> {
  if (type === "pubkey") return getAddressDecoder();
  if (type === "u64") return getU64Decoder();
  if (type === "i64") return getI64Decoder();
  if (type === "u8") return getU8Decoder();
  if (type === "bool") return getBooleanDecoder();
  if (typeof type === "object" && type.defined.name === "CampaignStatus") {
    return transformDecoder(getU8Decoder(), (index) => {
      const variant = statuses.type.variants[index];
      if (!variant)
        throw new Error("Unsupported campaign status in RPC account.");
      return variant.name;
    });
  }
  throw new Error("Unsupported campaign IDL field.");
}
const campaignDecoder = getStructDecoder(
  campaignType.type.fields.map(
    (field) => [field.name, fieldDecoder(field.type)] as const,
  ),
);
export const CAMPAIGN_DISCRIMINATOR = FUSE_IDL.accounts.find(
  (account) => account.name === "Campaign",
)!.discriminator;
export const CAMPAIGN_SIZE = 8 + campaignDecoder.fixedSize;
export function decodeCampaign(bytes: Uint8Array): CampaignData {
  if (
    bytes.length !== CAMPAIGN_SIZE ||
    !CAMPAIGN_DISCRIMINATOR.every((byte, i) => bytes[i] === byte)
  ) {
    throw new Error(
      "RPC account does not match the generated Campaign interface.",
    );
  }
  return campaignDecoder.decode(bytes.slice(8)) as unknown as CampaignData;
}
export const decodeBase64 = (value: string) =>
  Uint8Array.from(atob(value), (char) => char.charCodeAt(0));
export const encodeBase64 = (bytes: Uint8Array) =>
  btoa(String.fromCharCode(...bytes));
export function tokenAmount(raw: bigint, decimals: number): string {
  if (raw < 0n || !Number.isInteger(decimals) || decimals < 0 || decimals > 255)
    throw new Error("Invalid token amount.");
  if (!decimals) return raw.toString();
  const units = 10n ** BigInt(decimals);
  const fraction = (raw % units)
    .toString()
    .padStart(decimals, "0")
    .replace(/0+$/, "");
  return `${raw / units}${fraction ? `.${fraction}` : ""}`;
}
export function activationReason(
  campaign: CampaignData,
  chainTime: bigint,
): string | null {
  if (campaign.status !== "Open")
    return "This campaign is already settled or refunding.";
  if (chainTime >= campaign.deadline)
    return "The activation deadline has passed.";
  if (
    campaign.funded_seats !== campaign.required_seats ||
    campaign.escrowed_amount !== campaign.target_amount
  )
    return "Waiting for full funding.";
  if (!campaign.venue_approved || !campaign.instructor_approved)
    return "Waiting for both supplier approvals.";
  return null;
}
export function localnetConfig(
  rpcUrl = "http://127.0.0.1:8899",
  programId: string = PROGRAM_ID,
  network = "localnet",
): NetworkConfig {
  const url = new URL(rpcUrl);
  if (network !== "localnet")
    throw new Error(
      "Network mismatch: this page supports only Solana localnet.",
    );
  if (
    url.protocol !== "http:" ||
    !["127.0.0.1", "localhost", "[::1]"].includes(url.hostname) ||
    url.username ||
    url.password ||
    url.search ||
    url.hash
  ) {
    throw new Error(
      "Network mismatch: this proof of concept accepts only an HTTP loopback local validator RPC.",
    );
  }
  if (programId !== PROGRAM_ID)
    throw new Error(
      "Program ID mismatch: rebuild the interface from the deployed Rust program.",
    );
  return {
    rpcUrl: url.toString(),
    programId: address(programId),
    network: "localnet",
  };
}
export function networkConfig(
  rpcUrl = process.env.NEXT_PUBLIC_SOLANA_RPC_URL || DEVNET_RPC,
  programId: string = process.env.NEXT_PUBLIC_FUSE_PROGRAM_ID ||
    DEVNET_PROGRAM_ID,
  network = process.env.NEXT_PUBLIC_SOLANA_NETWORK || "devnet",
): NetworkConfig {
  if (network === "localnet") return localnetConfig(rpcUrl, programId, network);
  if (network !== "devnet" || new URL(rpcUrl).href !== `${DEVNET_RPC}/`)
    throw new Error(
      "Network mismatch: only canonical Solana Devnet or an explicit local validator is allowed.",
    );
  if (programId !== DEVNET_PROGRAM_ID)
    throw new Error(
      "Program ID mismatch: use the generated Devnet interface and verified deployment address.",
    );
  return {
    rpcUrl: DEVNET_RPC,
    programId: address(programId),
    network: "devnet",
  };
}
export function verifyGenesis(config: NetworkConfig, genesis: string): void {
  if (config.network === "devnet") {
    if (genesis !== DEVNET_GENESIS)
      throw new Error("Network mismatch: RPC does not report Solana Devnet.");
  } else if (
    ["5eykt", "EtWTR", "4uhc"].some((prefix) => genesis.startsWith(prefix))
  ) {
    throw new Error(
      "Network mismatch: local RPC reports a public Solana cluster.",
    );
  }
}
export const addressBytes = (value: Address) =>
  getAddressEncoder().encode(value);
